// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgaT8Uy235xCpV4Cr7vYj-p_Gn62b6yqk',
    appId: '1:18123541633:ios:86317c933f29d308949180',
    messagingSenderId: '18123541633',
    projectId: 'canada-immigration-daily',
    storageBucket: 'canada-immigration-daily.firebasestorage.app',
    iosBundleId: 'com.example.canadaImmigrationNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgaT8Uy235xCpV4Cr7vYj-p_Gn62b6yqk',
    appId: '1:18123541633:ios:86317c933f29d308949180',
    messagingSenderId: '18123541633',
    projectId: 'canada-immigration-daily',
    storageBucket: 'canada-immigration-daily.firebasestorage.app',
    iosBundleId: 'com.example.canadaImmigrationNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSXkM2VsvGVORStXOVysRsV-DItIUEXz4',
    appId: '1:18123541633:web:3a7cf158aa594d87949180',
    messagingSenderId: '18123541633',
    projectId: 'canada-immigration-daily',
    authDomain: 'canada-immigration-daily.firebaseapp.com',
    storageBucket: 'canada-immigration-daily.firebasestorage.app',
    measurementId: 'G-MR7JRE9TKG',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXkM2VsvGVORStXOVysRsV-DItIUEXz4',
    appId: '1:18123541633:web:3a7cf158aa594d87949180',
    messagingSenderId: '18123541633',
    projectId: 'canada-immigration-daily',
    authDomain: 'canada-immigration-daily.firebaseapp.com',
    storageBucket: 'canada-immigration-daily.firebasestorage.app',
    measurementId: 'G-MR7JRE9TKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCawr2tDyc8FkwGaJ-KMK1h3i-kfYVB0FE',
    appId: '1:18123541633:android:05d6dcded6f75858949180',
    messagingSenderId: '18123541633',
    projectId: 'canada-immigration-daily',
    storageBucket: 'canada-immigration-daily.firebasestorage.app',
  );

}